In [ ]:
import numpy as np
import numpy.typing as npt

poblacion: npt.NDArray[np.int_] = np.random.randint(0, 3, size=(10, 20), dtype=int)

print("Población inicial:")
print(poblacion)

Población inicial:
[[1 0 2 1 2 1 1 2 2 2 1 2 1 2 0 1 1 0 1 2]
 [2 1 0 0 2 2 2 0 0 0 0 1 2 1 2 0 0 0 0 1]
 [1 1 2 0 2 1 0 1 0 1 1 1 0 2 0 0 0 2 2 0]
 [0 1 2 2 1 0 0 0 0 0 2 2 1 1 1 2 2 1 0 2]
 [0 0 0 1 0 1 2 0 1 1 0 0 2 1 0 2 0 1 0 0]
 [0 0 1 2 1 0 1 0 1 2 0 0 1 2 0 0 2 0 1 2]
 [2 1 2 2 0 2 1 2 2 2 0 1 1 1 2 2 2 1 1 1]
 [1 1 0 0 0 1 0 0 1 2 2 0 1 2 1 1 1 1 0 1]
 [2 2 0 1 2 1 0 0 1 1 1 0 1 2 0 0 1 2 1 1]
 [2 2 0 2 1 2 2 2 2 0 0 2 1 0 1 1 0 0 2 2]]


In [ ]:
tercer_individuo: npt.NDArray[np.int_] = poblacion[2]
print("\nCromosoma del tercer individuo:")
print(tercer_individuo)


Cromosoma del tercer individuo:
[1 1 2 0 2 1 0 1 0 1 1 1 0 2 0 0 0 2 2 0]


In [ ]:
primeros_5_genes: npt.NDArray[np.int_] = poblacion[:, :5]
print("\nPrimeros 5 genes de todos los individuos:")
print(primeros_5_genes)


Primeros 5 genes de todos los individuos:
[[1 0 2 1 2]
 [2 1 0 0 2]
 [1 1 2 0 2]
 [0 1 2 2 1]
 [0 0 0 1 0]
 [0 0 1 2 1]
 [2 1 2 2 0]
 [1 1 0 0 0]
 [2 2 0 1 2]
 [2 2 0 2 1]]


In [5]:
indice_individuo: int = np.random.randint(0, 10)
indice_individuo

8

In [ ]:

individuo_mutado: npt.NDArray[np.int_] = poblacion[indice_individuo].copy()
individuo_mutado

array([2, 2, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 1, 1],
      dtype=int32)

In [8]:

ultimo_gen_actual: int = individuo_mutado[-1]
ultimo_gen_actual

np.int32(1)

In [10]:
alelos_posibles: list[int] = [0, 1, 2]
alelos_posibles.remove(ultimo_gen_actual)

nuevo_alelo: int = np.random.choice(alelos_posibles)

individuo_mutado[-1] = nuevo_alelo

print("\nIndividuo seleccionado para mutación:", indice_individuo)
print("Antes de la mutación:", poblacion[indice_individuo])
print("Después de la mutación:", individuo_mutado)


Individuo seleccionado para mutación: 8
Antes de la mutación: [2 2 0 1 2 1 0 0 1 1 1 0 1 2 0 0 1 2 1 1]
Después de la mutación: [2 2 0 1 2 1 0 0 1 1 1 0 1 2 0 0 1 2 1 0]


In [12]:
import numpy as np
import numpy.typing as npt

# Matriz A: 10 individuos, 10 genes cada uno
A: npt.NDArray[np.int_] = np.array([
    [1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0, 0, 1, 1, 0, 1],
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
    [0, 0, 1, 1, 1, 0, 0, 1, 1, 0],
    [1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
    [1, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
    [1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
])

In [ ]:
import random
indices: list = random.sample(range(A.shape[0]), 2)

padre1: npt.NDArray[np.int_] = A[indices[0]]
padre2: npt.NDArray[np.int_] = A[indices[1]]

print("Padre 1 (individuo", indices[0], "):", padre1)
print("Padre 2 (individuo", indices[1], "):", padre2)

Padre 1 (individuo 2 ): [1 1 1 0 0 1 1 0 0 1]
Padre 2 (individuo 1 ): [0 1 0 1 0 0 1 1 0 1]


In [15]:
genes_padre1: int = int(np.sum(padre1))
genes_padre2: int = int(np.sum(padre2))

print("\nCantidad de genes activos (1):")
print("Padre 1:", genes_padre1)
print("Padre 2:", genes_padre2)


Cantidad de genes activos (1):
Padre 1: 6
Padre 2: 5


In [16]:
if genes_padre1 > genes_padre2:
    print("El Padre 1 tiene mayor aptitud.")
elif genes_padre2 > genes_padre1:
    print("El Padre 2 tiene mayor aptitud.")
else:
    print("Ambos padres tienen la misma aptitud.")

El Padre 1 tiene mayor aptitud.


In [17]:
punto_corte: int = 5

hijo1: npt.NDArray[np.int_] = np.concatenate((padre1[:punto_corte], padre2[punto_corte:]))
hijo2: npt.NDArray[np.int_] = np.concatenate((padre2[:punto_corte], padre1[punto_corte:]))

In [18]:
print("Padre 1:", padre1)
print("Padre 2:", padre2)

print("\nHijo 1:", hijo1)
print("Hijo 2:", hijo2)

Padre 1: [1 1 1 0 0 1 1 0 0 1]
Padre 2: [0 1 0 1 0 0 1 1 0 1]

Hijo 1: [1 1 1 0 0 0 1 1 0 1]
Hijo 2: [0 1 0 1 0 1 1 0 0 1]


In [ ]:
import random
import numpy as np
import numpy.typing as npt

# Lista de tuplas: (Cromosoma de 8 genes, Fitness)
poblacion_completa: list = [
    ([1, 1, 1, 10, 1, 0, 1, 0], 5.6), ([1, 1, 1, 10, 1, 0, 1, 1], 6.8),
    ([0, 0, 1, 5, 0, 1, 1, 0], 9.2),  ([1, 0, 1, 8, 1, 1, 0, 0], 4.1),
    ([0, 1, 0, 3, 0, 0, 1, 1], 7.5),  ([1, 1, 0, 12, 1, 0, 0, 1], 3.2),
    ([0, 0, 0, 2, 0, 1, 1, 1], 8.9),  ([1, 0, 0, 7, 1, 1, 1, 0], 5.0),
    ([0, 1, 1, 4, 0, 0, 0, 1], 6.3),  ([1, 1, 1, 15, 0, 0, 1, 1], 2.1),
    ([0, 0, 1, 1, 1, 1, 0, 0], 9.8),  ([1, 0, 1, 9, 0, 1, 0, 1], 4.7),
    ([0, 1, 0, 6, 1, 0, 1, 0], 5.9),  ([1, 1, 0, 11, 0, 0, 0, 0], 3.8),
    ([0, 0, 0, 5, 1, 1, 1, 1], 7.1),  ([1, 0, 0, 3, 0, 1, 1, 0], 8.2),
    ([0, 1, 1, 8, 1, 0, 0, 1], 4.5),  ([1, 1, 1, 2, 0, 1, 0, 1], 8.5),
    ([0, 0, 1, 10, 0, 0, 1, 1], 3.9), ([0, 1, 0, 4, 1, 1, 0, 0], 7.8)
]

In [20]:
candidatos: list = random.sample(poblacion_completa, 3)

print("Candidatos seleccionados:")
for c in candidatos:
    print(c)

Candidatos seleccionados:
([1, 0, 0, 7, 1, 1, 1, 0], 5.0)
([1, 1, 1, 15, 0, 0, 1, 1], 2.1)
([1, 0, 1, 9, 0, 1, 0, 1], 4.7)


In [28]:
candidatos_ordenados = sorted(candidatos, key=lambda x: x[1], reverse=True)

print("\nCandidatos ordenados por fitness:")
for c in candidatos_ordenados:
    print(c)


Candidatos ordenados por fitness:
([1, 0, 0, 7, 1, 1, 1, 0], 5.0)
([1, 0, 1, 9, 0, 1, 0, 1], 4.7)
([1, 1, 1, 15, 0, 0, 1, 1], 2.1)


In [29]:
padre1: tuple = candidatos_ordenados[0]
padre2: tuple = candidatos_ordenados[1]

In [30]:
crom_padre1: list= padre1[0]
crom_padre2: list = padre2[0]

print("\nPadre 1:", crom_padre1, "Fitness:", padre1[1])
print("Padre 2:", crom_padre2, "Fitness:", padre2[1])


Padre 1: [1, 0, 0, 7, 1, 1, 1, 0] Fitness: 5.0
Padre 2: [1, 0, 1, 9, 0, 1, 0, 1] Fitness: 4.7


In [31]:
punto_cruce: int = 4

hijo1: list = crom_padre1[:punto_cruce] + crom_padre2[punto_cruce:]
hijo2: list = crom_padre2[:punto_cruce] + crom_padre1[punto_cruce:]

In [32]:
print("\nResultado del cruce:")
print("Hijo 1:", hijo1)
print("Hijo 2:", hijo2)


Resultado del cruce:
Hijo 1: [1, 0, 0, 7, 0, 1, 0, 1]
Hijo 2: [1, 0, 1, 9, 1, 1, 1, 0]
