Ejercicio 1: Selección aleatoria de elementos

    Dado un conjunto de números del 1 al 8, selecciona 5 números aleatorios con reemplazo, usando la función choice
    Preguntas
        ¿Qué sucede si cambias replace=True a replace=False?
        ¿Cómo harías para obtener una selección de 3 elementos sin repetición?

In [ ]:
import numpy as np

numeros = np.arange(1, 9) 

seleccion = np.random.choice(numeros, 5, replace=True)
print("Selección con reemplazo:", seleccion)

Selección con reemplazo: [6 2 7 2 7]


In [2]:
seleccion = np.random.choice(numeros, 5, replace=False)
print("Selección sin reemplazo:", seleccion)

Selección sin reemplazo: [2 5 7 3 8]


Ejercicio 2: Generar todas las combinaciones

    Dado el conjunto {A, B, C, D}, genera todas las combinaciones de tamaño 2 sin importar el orden.
    Preguntas
        ¿Cuántas combinaciones de 3 elementos puedes generar?
        ¿Cómo se verían las combinaciones si permitiéramos repetición?


In [6]:
from itertools import combinations

conjunto = ['A', 'B', 'C', 'D']

comb = list(combinations(conjunto, 2))
print(comb)
print("Total:", len(comb))

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]
Total: 6


In [4]:
comb3 = list(combinations(conjunto, 3))
print(comb3)
print("Total:", len(comb3))

[('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'C', 'D'), ('B', 'C', 'D')]
Total: 4


Ejercicio 3: Generar todas las permutaciones

    Dado el conjunto {A, C , G, T}, genera todas las permutaciones de tamaño 2.
    Preguntas
        ¿Cómo cambia el número de resultados si usamos permutations(numeros, 3)?
        ¿Cómo podrías modificar el código para incluir repetición?


In [7]:
from itertools import permutations

conjunto = ['A', 'C', 'G', 'T']

perm = list(permutations(conjunto, 2))
print(perm)
print("Total:", len(perm))

[('A', 'C'), ('A', 'G'), ('A', 'T'), ('C', 'A'), ('C', 'G'), ('C', 'T'), ('G', 'A'), ('G', 'C'), ('G', 'T'), ('T', 'A'), ('T', 'C'), ('T', 'G')]
Total: 12


In [8]:
perm3 = list(permutations(conjunto, 3))
print(len(perm3))

24


In [11]:
from itertools import product

perm_rep = list(product(conjunto, repeat=2))
print(perm_rep)
print("Total: ", len(perm_rep))

[('A', 'A'), ('A', 'C'), ('A', 'G'), ('A', 'T'), ('C', 'A'), ('C', 'C'), ('C', 'G'), ('C', 'T'), ('G', 'A'), ('G', 'C'), ('G', 'G'), ('G', 'T'), ('T', 'A'), ('T', 'C'), ('T', 'G'), ('T', 'T')]
Total:  16


Ejercicio 4: Selección de individuos por torneo

    Dada la siguiente población y sus aptitudes, seleccionar 3 individuos al azar; mostrar los individuos y sus correspondientes aptitudes; y seleccionar al mejor según su aptitud.
    Población representada por valores de aptitud (fitness)
        poblacion = np.array(['A', 'B', 'C', 'D', 'E'])
        aptitud = np.array([10, 30, 20, 50, 40]) # Mayor es mejor


In [12]:
import numpy as np

poblacion = np.array(['A', 'B', 'C', 'D', 'E'])
aptitud = np.array([10, 30, 20, 50, 40])

In [13]:
indices = np.random.choice(len(poblacion), 3, replace=False)

individuos = poblacion[indices]
fitness = aptitud[indices]

print("Individuos seleccionados:", individuos)
print("Aptitudes:", fitness)

Individuos seleccionados: ['C' 'B' 'E']
Aptitudes: [20 30 40]


In [14]:
mejor_indice = np.argmax(fitness)

mejor_individuo = individuos[mejor_indice]
mejor_aptitud = fitness[mejor_indice]

print("Ganador del torneo:", mejor_individuo)
print("Aptitud:", mejor_aptitud)

Ganador del torneo: E
Aptitud: 40


    Ejercicio 5: Generación de una Población Inicial Sin Repeticiones

        En algoritmos genéticos, la población inicial a menudo se genera con soluciones distintas. Por ejemplo, para el problema de las 8 Reinas, queremos que cada solución tenga una permutación única de las filas sin repetición de los elementos, por ejemplo [1,4,5,6,7,8,3,2]. Cada columna representa la posición en esa columa y el valor representa la fila de la reina. Puede iniciar ya sea en 1 como en el ejemplo anterior o en 0, [0,3,4,5,6,7,3,1]

        Generar una población inicial de 50 individuos sin repeticiones

        Generar una población inicial de 50 individuos permitiendo que haya repeticiones de los números


In [15]:
import numpy as np

poblacion = []

for i in range(50):
    individuo = np.random.permutation(8) + 1
    poblacion.append(individuo)

poblacion = np.array(poblacion)

print(poblacion)

[[7 3 2 6 8 4 1 5]
 [7 6 5 4 2 8 3 1]
 [2 1 4 6 5 7 8 3]
 [2 3 4 7 8 6 1 5]
 [3 7 5 1 6 2 8 4]
 [1 3 8 5 7 6 2 4]
 [8 6 2 5 1 3 7 4]
 [3 7 5 6 1 8 2 4]
 [6 2 5 7 4 3 1 8]
 [6 5 7 8 1 4 3 2]
 [3 4 8 5 2 1 7 6]
 [8 7 5 1 2 6 3 4]
 [4 1 5 6 7 2 8 3]
 [8 6 2 7 4 3 5 1]
 [3 5 2 7 6 1 4 8]
 [7 1 2 5 4 6 3 8]
 [3 7 1 4 6 2 8 5]
 [2 1 3 6 7 4 5 8]
 [5 3 2 6 4 8 7 1]
 [4 8 1 6 7 3 2 5]
 [5 6 3 7 4 1 2 8]
 [5 7 1 8 4 2 6 3]
 [3 2 6 5 8 4 1 7]
 [1 3 5 4 8 2 6 7]
 [5 3 4 1 2 7 8 6]
 [8 1 7 3 2 4 5 6]
 [6 5 4 7 1 3 8 2]
 [7 2 6 8 4 1 5 3]
 [3 6 5 7 2 8 1 4]
 [3 2 6 7 1 4 8 5]
 [5 1 7 3 4 2 8 6]
 [2 4 7 1 3 6 8 5]
 [2 7 1 4 6 5 8 3]
 [2 8 1 3 4 7 5 6]
 [1 4 3 2 5 8 6 7]
 [6 3 1 4 2 8 5 7]
 [8 7 3 6 5 2 4 1]
 [1 2 5 4 3 8 7 6]
 [1 6 2 8 3 4 5 7]
 [2 4 1 7 8 5 6 3]
 [2 8 1 3 4 6 7 5]
 [5 3 8 1 7 6 4 2]
 [5 1 4 8 7 2 6 3]
 [3 5 4 1 8 7 6 2]
 [3 8 5 6 2 4 7 1]
 [6 4 1 7 5 2 3 8]
 [1 3 2 8 5 6 7 4]
 [1 4 3 7 6 2 8 5]
 [4 1 7 8 2 6 3 5]
 [3 6 4 2 8 1 5 7]]


In [16]:
poblacion = []

for i in range(50):
    individuo = np.random.randint(1, 9, size=8)
    poblacion.append(individuo)

poblacion = np.array(poblacion)

print(poblacion)

[[3 1 1 1 4 4 4 6]
 [8 3 2 6 8 5 7 7]
 [8 3 6 4 6 3 6 2]
 [3 5 4 2 2 7 4 6]
 [6 2 5 3 4 8 1 3]
 [3 2 6 4 7 7 2 2]
 [5 5 1 6 5 8 4 3]
 [5 8 1 5 6 8 5 3]
 [7 7 1 1 5 8 4 1]
 [1 5 7 8 2 5 6 6]
 [1 3 7 6 1 8 2 1]
 [1 8 2 5 1 4 8 5]
 [3 7 1 8 7 7 3 7]
 [1 3 8 7 7 7 8 4]
 [2 3 3 4 2 2 7 8]
 [2 8 5 1 5 6 4 8]
 [8 7 1 7 1 4 4 3]
 [8 5 1 1 5 8 3 5]
 [3 2 6 6 5 4 4 1]
 [3 2 2 6 2 4 1 7]
 [8 5 1 5 5 7 2 4]
 [1 1 4 7 6 3 5 6]
 [4 3 5 6 4 3 2 3]
 [6 4 1 4 8 4 1 7]
 [6 8 6 3 6 4 2 4]
 [4 1 1 6 8 2 1 6]
 [5 8 2 2 4 7 6 4]
 [6 5 4 7 1 3 4 6]
 [5 8 3 2 1 4 3 8]
 [2 3 6 8 5 1 3 4]
 [4 1 4 5 8 2 7 5]
 [8 6 7 7 7 7 1 4]
 [5 7 7 8 6 3 6 4]
 [8 5 7 7 1 3 5 6]
 [4 4 5 8 3 8 2 7]
 [6 1 4 6 7 8 2 5]
 [5 2 8 7 3 2 2 1]
 [1 7 5 8 3 4 8 8]
 [6 4 6 7 4 5 4 1]
 [1 3 3 1 6 7 7 2]
 [2 7 6 7 7 8 2 5]
 [1 7 2 6 6 3 7 5]
 [7 1 6 7 1 6 1 7]
 [2 5 4 8 2 3 4 4]
 [2 7 6 3 5 1 6 3]
 [4 1 6 2 8 3 6 7]
 [8 3 5 3 3 2 8 1]
 [8 3 5 8 1 5 5 1]
 [7 7 6 7 5 8 7 2]
 [6 3 1 2 5 7 5 8]]
