In [2]:
# Función que imprime al individuo en representación de tablero en formato textual
def imprimir_tablero(individuo:list, N: int=8) -> None:
    # Imprimir formato de tablero
    if individuo:
        for i in range(N):
            linea = ""
            for j in range(N):
                if individuo[j] == i:
                    linea += "Q "
                else:
                    linea += ". "
            print(linea)

In [3]:
# Ejemplo de la impresión de un individuo
imprimir_tablero([6,1,3,2,5,7,4,0])

. . . . . . . Q 
. Q . . . . . . 
. . . Q . . . . 
. . Q . . . . . 
. . . . . . Q . 
. . . . Q . . . 
Q . . . . . . . 
. . . . . Q . . 


In [4]:
import numpy as np
import numpy.typing as npt
import random

def generar_poblacion() -> npt.NDArray[np.int8]:
    """
    Genera una población aleatoria.

    Retorna
    -------
    npt.NDArray[np.int8]
        Matriz de numpy de forma (100, 8)
        - 100 individuos
        - 8 genes por individuo
        - valores entre 0 y 7
    """
    # TODO: Generar una población aleatoria conformada por individuos que contienen 8 genes.
    # Cada dimensión representa la columna de la posición de la reina, se tiene como máximo 8 columnas.
    # El valor del gen representa la fila donde está colocada la reina, se tiene los valores 0-7,
    # considerando el cero como la primera fila.

    poblacion: npt.NDArray[np.int8] = np.random.randint(0,8, (100,8))
    return poblacion


In [ ]:
poblacion = generar_poblacion()
poblacion 

array([[6, 7, 7, 1, 4, 0, 2, 6],
       [0, 6, 0, 6, 2, 5, 6, 7],
       [3, 7, 0, 7, 3, 6, 1, 5],
       [3, 1, 3, 1, 0, 4, 7, 3],
       [1, 3, 1, 2, 4, 2, 2, 0],
       [7, 4, 1, 7, 0, 7, 1, 4],
       [2, 2, 1, 2, 1, 6, 7, 5],
       [3, 1, 0, 0, 1, 0, 5, 1],
       [5, 0, 1, 1, 0, 4, 7, 2],
       [4, 4, 0, 2, 0, 6, 3, 5],
       [3, 6, 2, 0, 3, 3, 4, 3],
       [1, 0, 7, 0, 2, 2, 3, 4],
       [0, 0, 6, 4, 7, 6, 0, 6],
       [7, 7, 6, 6, 3, 2, 4, 7],
       [7, 2, 6, 7, 7, 6, 2, 6],
       [2, 6, 0, 4, 0, 4, 6, 5],
       [7, 6, 1, 2, 5, 4, 4, 4],
       [6, 7, 1, 3, 4, 1, 3, 0],
       [3, 3, 4, 7, 3, 7, 3, 4],
       [4, 6, 2, 5, 1, 7, 2, 6],
       [1, 1, 3, 0, 2, 2, 3, 4],
       [4, 7, 6, 2, 5, 3, 4, 2],
       [0, 4, 4, 7, 4, 6, 6, 5],
       [6, 1, 4, 5, 0, 5, 3, 7],
       [3, 6, 3, 6, 6, 4, 2, 7],
       [2, 5, 6, 6, 4, 6, 5, 7],
       [0, 4, 7, 1, 4, 0, 3, 3],
       [1, 3, 7, 0, 3, 5, 1, 7],
       [5, 2, 6, 0, 6, 3, 1, 3],
       [2, 6, 0, 7, 1, 4, 5, 1],
       [7,

In [29]:

def calcular_aptitud(individuo: npt.NDArray[np.int8]) -> list[int]:
    """Calcula el número de conflictos (aptitud o fitness)."""
    fitnes: list[int] = []
    # TODO: Calcula el número de conflictos si un par de reinas están en la misma fila
    # o si están en la misma diagonal.
    # No pueden estar en la misma columna debido a que la representación no lo permite,
    # solo hay una reina por columna.
    for indi in individuo:
        conflictos: int = 0
        for i in range(0,8):
            for k in range(i+1, 8):
                if indi[i] == indi[k]:
                    conflictos += 1
                if abs(i - k) == abs(indi[i] - indi[k]):
                    conflictos += 1
        fitnes.append(conflictos)
    return fitnes
    


In [44]:
aptitud = calcular_aptitud(poblacion)

In [45]:
poblacion = list(zip(poblacion, aptitud))


In [46]:
poblacion

[(array([6, 7, 7, 1, 4, 0, 2, 6]), 6),
 (array([0, 6, 0, 6, 2, 5, 6, 7]), 11),
 (array([3, 7, 0, 7, 3, 6, 1, 5]), 4),
 (array([3, 1, 3, 1, 0, 4, 7, 3]), 7),
 (array([1, 3, 1, 2, 4, 2, 2, 0]), 7),
 (array([7, 4, 1, 7, 0, 7, 1, 4]), 6),
 (array([2, 2, 1, 2, 1, 6, 7, 5]), 10),
 (array([3, 1, 0, 0, 1, 0, 5, 1]), 10),
 (array([5, 0, 1, 1, 0, 4, 7, 2]), 7),
 (array([4, 4, 0, 2, 0, 6, 3, 5]), 5),
 (array([3, 6, 2, 0, 3, 3, 4, 3]), 10),
 (array([1, 0, 7, 0, 2, 2, 3, 4]), 10),
 (array([0, 0, 6, 4, 7, 6, 0, 6]), 9),
 (array([7, 7, 6, 6, 3, 2, 4, 7]), 8),
 (array([7, 2, 6, 7, 7, 6, 2, 6]), 11),
 (array([2, 6, 0, 4, 0, 4, 6, 5]), 7),
 (array([7, 6, 1, 2, 5, 4, 4, 4]), 8),
 (array([6, 7, 1, 3, 4, 1, 3, 0]), 8),
 (array([3, 3, 4, 7, 3, 7, 3, 4]), 12),
 (array([4, 6, 2, 5, 1, 7, 2, 6]), 5),
 (array([1, 1, 3, 0, 2, 2, 3, 4]), 10),
 (array([4, 7, 6, 2, 5, 3, 4, 2]), 8),
 (array([0, 4, 4, 7, 4, 6, 6, 5]), 8),
 (array([6, 1, 4, 5, 0, 5, 3, 7]), 6),
 (array([3, 6, 3, 6, 6, 4, 2, 7]), 6),
 (array([2, 5, 6,

In [54]:

def seleccionar_padres(
    poblacion: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    """Selecciona dos padres usando selección por torneo."""

    # TODO: Seleccionar de forma aleatoria 4 individuos
    # Sugerencia usar: random.sample

    torneo: list[int] = random.sample(poblacion, 4) # O usar otra representación para seleccionar, 
                             # como empaquetar a los individuos (padres) junto con su aptitud

    print("Candidatos seleccionados:")
    for c in torneo:
        print(c)

    candidatos_ordenados = sorted(torneo, key=lambda x: x[1], reverse=True)

    print("\nCandidatos ordenados por fitness:")
    for c in candidatos_ordenados:
        print(c)
    # Ordenar a los individuos seleccionados de acuerdo a la aptitud y seleccionar a los 2 mejores


    padre1: npt.NDArray[np.int8] = candidatos_ordenados[0]
    padre2: npt.NDArray[np.int8] = candidatos_ordenados[1]

    return padre1, padre2


In [55]:
seleccionar_padres(poblacion)

Candidatos seleccionados:
(array([7, 7, 6, 6, 3, 2, 4, 7]), 8)
(array([2, 6, 0, 7, 1, 4, 5, 1]), 3)
(array([4, 7, 6, 2, 5, 3, 4, 2]), 8)
(array([4, 0, 5, 3, 0, 7, 1, 6]), 4)

Candidatos ordenados por fitness:
(array([7, 7, 6, 6, 3, 2, 4, 7]), 8)
(array([4, 7, 6, 2, 5, 3, 4, 2]), 8)
(array([4, 0, 5, 3, 0, 7, 1, 6]), 4)
(array([2, 6, 0, 7, 1, 4, 5, 1]), 3)


((array([7, 7, 6, 6, 3, 2, 4, 7]), 8), (array([4, 7, 6, 2, 5, 3, 4, 2]), 8))

In [ ]:

def cruzar(
    padre1: npt.NDArray[np.int8],
    padre2: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    """Realiza crossover entre dos padres."""

    # TODO: Obtener un punto de cruza aleatorio y obtener dos hijos
    hijo1: npt.NDArray[np.int8] = None
    hijo2: npt.NDArray[np.int8] = None

    return hijo1, hijo2


def mutar(
    individuo: npt.NDArray[np.int8],
    tasa_mutacion: float = 0.1
) -> npt.NDArray[np.int8]:
    """Realiza mutación con una probabilidad dada."""

    if np.random.random() < tasa_mutacion:
        # Se aplica la mutación, solo si pasó el umbral aleatorio.

        # TODO: obtener de forma aleatoria la posición del gen por sustituir,
        # con un nuevo valor aleatorio dentro del rango permitido [0, 7]

        pass

    return individuo

def algoritmo_genetico() -> npt.NDArray[np.int8] | None:
    """Resuelve el problema de las 8 reinas usando un algoritmo genético."""

    # Parámetros
    # TODO: Definir los parámetros
    tamano_poblacion: int = 0
    max_generaciones: int = 0
    tasa_mutacion: float = 0.1

    # TODO: Generar población inicial
    poblacion: npt.NDArray[np.int8] = generar_poblacion()

    for generacion in range(max_generaciones):

        # TODO: Calcular aptitudes de toda la población para verificar si ya hay una solución
        aptitudes: npt.NDArray[np.int8] = None

        # TODO: Verificar si hay solución
        # Si hay solución termina el algoritmo, y retornar la solución
        # De lo contrario continua con el proceso de evolución

        # Nueva generación
        nueva_poblacion: list[npt.NDArray[np.int8]] = []

        padre1: npt.NDArray[np.int8]
        padre2: npt.NDArray[np.int8]
        hijo1: npt.NDArray[np.int8]
        hijo2: npt.NDArray[np.int8]

        for _ in range(tamano_poblacion // 2):
            padre1, padre2 = seleccionar_padres(poblacion, aptitudes)

            hijo1, hijo2 = cruzar(padre1, padre2)

            hijo1 = mutar(hijo1, tasa_mutacion)
            hijo2 = mutar(hijo2, tasa_mutacion)

            # Construye a la nueva población con los hijos
            nueva_poblacion.append(hijo1)
            nueva_poblacion.append(hijo2)

        # Sustituye a la población completa de padres por los hijos
        poblacion = np.array(nueva_poblacion, dtype=np.int8)

    print("No se encontró solución en el número máximo de generaciones.")
    return None

In [ ]:
# Ejecutar el algoritmo genético

solucion: npt.NDArray[np.int8] | None = algoritmo_genetico()

if solucion:
    imprimir_tablero(solucion)
