In [110]:
# Función que imprime al individuo en representación de tablero en formato textual
def imprimir_tablero(individuo:list, N: int=8) -> None:
    # Imprimir formato de tablero
    if individuo:
        for i in range(N):
            linea = ""
            for j in range(N):
                if individuo[j] == i:
                    linea += "Q "
                else:
                    linea += ". "
            print(linea)

In [111]:
# Ejemplo de la impresión de un individuo
imprimir_tablero([6,1,3,2,5,7,4,0])

. . . . . . . Q 
. Q . . . . . . 
. . . Q . . . . 
. . Q . . . . . 
. . . . . . Q . 
. . . . Q . . . 
Q . . . . . . . 
. . . . . Q . . 


In [112]:
import numpy as np
import numpy.typing as npt
import random

def generar_poblacion() -> npt.NDArray[np.int8]:
    """
    Genera una población aleatoria.

    Retorna
    -------
    npt.NDArray[np.int8]
        Matriz de numpy de forma (100, 8)
        - 100 individuos
        - 8 genes por individuo
        - valores entre 0 y 7
    """
    # TODO: Generar una población aleatoria conformada por individuos que contienen 8 genes.
    # Cada dimensión representa la columna de la posición de la reina, se tiene como máximo 8 columnas.
    # El valor del gen representa la fila donde está colocada la reina, se tiene los valores 0-7,
    # considerando el cero como la primera fila.

    poblacion: npt.NDArray[np.int8] = np.random.randint(0,8, (100,8))
    return poblacion


In [113]:
poblacion = generar_poblacion()
poblacion 

array([[6, 2, 2, 3, 4, 1, 4, 6],
       [6, 0, 7, 1, 2, 5, 1, 1],
       [7, 1, 7, 6, 4, 7, 7, 4],
       [3, 7, 3, 0, 4, 4, 2, 2],
       [0, 7, 5, 1, 5, 1, 4, 0],
       [2, 0, 3, 3, 7, 6, 4, 6],
       [3, 4, 4, 1, 0, 7, 7, 1],
       [5, 4, 3, 2, 5, 6, 1, 7],
       [0, 2, 0, 2, 0, 0, 2, 6],
       [6, 4, 1, 3, 7, 3, 6, 3],
       [5, 4, 0, 0, 5, 0, 6, 5],
       [7, 6, 0, 3, 0, 1, 2, 7],
       [6, 6, 2, 4, 4, 5, 5, 4],
       [2, 7, 0, 6, 6, 1, 5, 6],
       [6, 0, 6, 3, 1, 7, 4, 6],
       [7, 7, 7, 4, 4, 0, 2, 6],
       [4, 6, 4, 7, 2, 0, 4, 4],
       [2, 0, 4, 5, 3, 3, 5, 3],
       [6, 6, 0, 4, 7, 4, 5, 6],
       [0, 5, 5, 1, 5, 0, 0, 3],
       [7, 1, 1, 5, 4, 4, 1, 2],
       [3, 2, 5, 4, 7, 4, 7, 0],
       [1, 0, 6, 1, 5, 3, 2, 7],
       [2, 0, 4, 6, 5, 2, 3, 3],
       [6, 1, 5, 4, 5, 5, 0, 4],
       [2, 1, 2, 3, 2, 5, 6, 5],
       [2, 2, 3, 1, 4, 5, 7, 0],
       [4, 0, 2, 0, 4, 0, 3, 1],
       [1, 2, 2, 4, 6, 6, 4, 7],
       [5, 4, 1, 4, 7, 3, 3, 2],
       [3,

In [114]:

def calcular_aptitud(individuo: npt.NDArray[np.int8]) -> list[int]:
    """Calcula el número de conflictos (aptitud o fitness)."""
    fitnes: list[int] = []
    # TODO: Calcula el número de conflictos si un par de reinas están en la misma fila
    # o si están en la misma diagonal.
    # No pueden estar en la misma columna debido a que la representación no lo permite,
    # solo hay una reina por columna.
    for indi in individuo:
        conflictos: int = 0
        for i in range(0,8):
            for k in range(i+1, 8):
                if indi[i] == indi[k]:
                    conflictos += 1
                if abs(i - k) == abs(indi[i] - indi[k]):
                    conflictos += 1
        fitnes.append(conflictos)
    return fitnes

In [115]:
aptitud = calcular_aptitud(poblacion)

In [116]:
poblacion = list(zip(poblacion, aptitud))


In [117]:
poblacion

[(array([6, 2, 2, 3, 4, 1, 4, 6], dtype=int32), 9),
 (array([6, 0, 7, 1, 2, 5, 1, 1], dtype=int32), 5),
 (array([7, 1, 7, 6, 4, 7, 7, 4], dtype=int32), 9),
 (array([3, 7, 3, 0, 4, 4, 2, 2], dtype=int32), 8),
 (array([0, 7, 5, 1, 5, 1, 4, 0], dtype=int32), 5),
 (array([2, 0, 3, 3, 7, 6, 4, 6], dtype=int32), 5),
 (array([3, 4, 4, 1, 0, 7, 7, 1], dtype=int32), 6),
 (array([5, 4, 3, 2, 5, 6, 1, 7], dtype=int32), 10),
 (array([0, 2, 0, 2, 0, 0, 2, 6], dtype=int32), 12),
 (array([6, 4, 1, 3, 7, 3, 6, 3], dtype=int32), 7),
 (array([5, 4, 0, 0, 5, 0, 6, 5], dtype=int32), 11),
 (array([7, 6, 0, 3, 0, 1, 2, 7], dtype=int32), 8),
 (array([6, 6, 2, 4, 4, 5, 5, 4], dtype=int32), 10),
 (array([2, 7, 0, 6, 6, 1, 5, 6], dtype=int32), 6),
 (array([6, 0, 6, 3, 1, 7, 4, 6], dtype=int32), 5),
 (array([7, 7, 7, 4, 4, 0, 2, 6], dtype=int32), 8),
 (array([4, 6, 4, 7, 2, 0, 4, 4], dtype=int32), 10),
 (array([2, 0, 4, 5, 3, 3, 5, 3], dtype=int32), 11),
 (array([6, 6, 0, 4, 7, 4, 5, 6], dtype=int32), 9),
 (arra

In [118]:

def seleccionar_padres(
    poblacion: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    """Selecciona dos padres usando selección por torneo."""

    # TODO: Seleccionar de forma aleatoria 4 individuos
    # Sugerencia usar: random.sample

    torneo: list[int] = random.sample(poblacion, 4) # O usar otra representación para seleccionar, 
                             # como empaquetar a los individuos (padres) junto con su aptitud


    # Ordenar a los individuos seleccionados de acuerdo a la aptitud y seleccionar a los 2 mejores
    candidatos_ordenados = sorted(torneo, key=lambda x: x[1])

    padre1: npt.NDArray[np.int8] = candidatos_ordenados[0]
    padre2: npt.NDArray[np.int8] = candidatos_ordenados[1]

    return padre1, padre2


In [119]:
padre1, padre2 = seleccionar_padres(poblacion)
print(padre1)
print(padre2)

(array([3, 7, 2, 5, 7, 2, 0, 4], dtype=int32), 6)
(array([3, 7, 3, 0, 4, 4, 2, 2], dtype=int32), 8)


In [120]:

def cruzar(
    padre1: npt.NDArray[np.int8],
    padre2: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    
    """Realiza crossover entre dos padres."""

    # TODO: Obtener un punto de cruza aleatorio y obtener dos hijos

    punto_cruce: int = random.randint(1,6)

    crom_padre1: list= padre1[0]
    crom_padre2: list = padre2[0]


    hijo1: npt.NDArray[np.int8] = np.concatenate((crom_padre1[:punto_cruce],crom_padre2[punto_cruce:]))
    hijo2: npt.NDArray[np.int8] = np.concatenate((crom_padre2[:punto_cruce], crom_padre1[punto_cruce:]))

    return hijo1, hijo2


In [121]:
hijo1, hijo2 = cruzar(padre1, padre2)

In [122]:
print(hijo1)
print(hijo2)

[3 7 2 5 4 4 2 2]
[3 7 3 0 7 2 0 4]


In [123]:
def mutar(
    individuo: npt.NDArray[np.int8],
    tasa_mutacion: float = 0.1
) -> npt.NDArray[np.int8]:
    """Realiza mutación con una probabilidad dada."""

    if np.random.random() < tasa_mutacion:
        # Se aplica la mutación, solo si pasó el umbral aleatorio.

        # TODO: obtener de forma aleatoria la posición del gen por sustituir,
        # con un nuevo valor aleatorio dentro del rango permitido [0, 7]

        valor_mutacion = random.randint(0,7)
        indice_mutacion = random.randint(0,7)
        individuo[indice_mutacion] = valor_mutacion

    return individuo


In [124]:
print("Antes: ", hijo1)
hijo_mutado = mutar(hijo1, 0.8)
print("Despues: ",hijo_mutado)

Antes:  [3 7 2 5 4 4 2 2]
Despues:  [3 7 2 5 4 4 2 2]


In [125]:

def algoritmo_genetico() -> npt.NDArray[np.int8] | None:
    """Resuelve el problema de las 8 reinas usando un algoritmo genético."""

    # Parámetros
    # TODO: Definir los parámetros
    tamano_poblacion: int = 100
    max_generaciones: int = 300
    tasa_mutacion: float = 0.10

    # TODO: Generar población inicial
    poblacion: npt.NDArray[np.int8] = generar_poblacion()

    for generacion in range(max_generaciones):

        # TODO: Calcular aptitudes de toda la población para verificar si ya hay una solución
        aptitudes: npt.NDArray[np.int8] = calcular_aptitud(poblacion)

        # TODO: Verificar si hay solución
        if 0 in aptitudes:
            posicion = np.where(aptitudes == 0)[0][0]
            solucion = poblacion[posicion]
            return solucion
        # Si hay solución termina el algoritmo, y retornar la solución
        # De lo contrario continua con el proceso de evolución

        # Nueva generación
        nueva_poblacion: list[npt.NDArray[np.int8]] = []

        padre1: npt.NDArray[np.int8]
        padre2: npt.NDArray[np.int8]
        hijo1: npt.NDArray[np.int8]
        hijo2: npt.NDArray[np.int8]
        
        poblacion = list(zip(poblacion, aptitudes))

        for _ in range(tamano_poblacion // 2):
            padre1, padre2 = seleccionar_padres(poblacion)

            hijo1, hijo2 = cruzar(padre1, padre2)

            hijo1 = mutar(hijo1, tasa_mutacion)
            hijo2 = mutar(hijo2, tasa_mutacion)

            # Construye a la nueva población con los hijos
            nueva_poblacion.append(hijo1)
            nueva_poblacion.append(hijo2)

        # Sustituye a la población completa de padres por los hijos
        poblacion = np.array(nueva_poblacion, dtype=np.int8)

    print("No se encontró solución en el número máximo de generaciones.")
    return None

In [126]:
# Ejecutar el algoritmo genético

solucion: npt.NDArray[np.int8] | None = algoritmo_genetico()

if solucion:
    imprimir_tablero(solucion)


ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.