In [66]:
def imprimir_tablero(individuo, N: int = 8) -> None:
    if individuo is None:
        return
    
    linea = "+---" * N + "+"

    for i in range(N):
        print(linea)
        fila = ""
        for j in range(N):
            if individuo[j] == i:
                fila += "| Q "
            else:
                fila += "|   "
        fila += "|"
        print(fila)

    print(linea)

In [27]:
# Ejemplo de la impresión de un individuo
imprimir_tablero([6,1,3,2,5,7,4,0])

. . . . . . . Q 
. Q . . . . . . 
. . . Q . . . . 
. . Q . . . . . 
. . . . . . Q . 
. . . . Q . . . 
Q . . . . . . . 
. . . . . Q . . 


In [28]:
import numpy as np
import numpy.typing as npt
import random

def generar_poblacion() -> npt.NDArray[np.int8]:
    """
    Genera una población aleatoria.

    Retorna
    -------
    npt.NDArray[np.int8]
        Matriz de numpy de forma (100, 8)
        - 100 individuos
        - 8 genes por individuo
        - valores entre 0 y 7
    """
    # TODO: Generar una población aleatoria conformada por individuos que contienen 8 genes.
    # Cada dimensión representa la columna de la posición de la reina, se tiene como máximo 8 columnas.
    # El valor del gen representa la fila donde está colocada la reina, se tiene los valores 0-7,
    # considerando el cero como la primera fila.

    poblacion: npt.NDArray[np.int8] = np.random.randint(0,8, (100,8))
    return poblacion


In [29]:
poblacion = generar_poblacion()
poblacion 

array([[1, 5, 4, 3, 7, 3, 7, 5],
       [2, 4, 3, 5, 0, 6, 4, 3],
       [1, 1, 0, 5, 4, 1, 7, 5],
       [2, 5, 4, 0, 4, 5, 1, 5],
       [1, 5, 2, 7, 4, 1, 3, 3],
       [0, 5, 3, 5, 2, 4, 0, 7],
       [3, 0, 2, 3, 5, 7, 5, 3],
       [1, 0, 0, 5, 6, 5, 6, 7],
       [0, 0, 1, 3, 6, 7, 4, 6],
       [6, 0, 6, 7, 3, 1, 1, 3],
       [0, 4, 7, 4, 6, 5, 4, 0],
       [6, 0, 2, 3, 5, 6, 6, 6],
       [2, 3, 5, 0, 3, 3, 2, 2],
       [0, 0, 0, 1, 0, 6, 7, 5],
       [2, 4, 3, 2, 7, 1, 4, 0],
       [1, 0, 3, 2, 4, 1, 1, 2],
       [2, 1, 6, 5, 6, 5, 2, 5],
       [0, 6, 0, 4, 0, 6, 6, 4],
       [0, 5, 3, 4, 4, 6, 0, 4],
       [0, 5, 1, 5, 0, 0, 7, 0],
       [4, 5, 1, 7, 5, 7, 3, 3],
       [3, 7, 4, 6, 7, 1, 3, 4],
       [3, 5, 5, 2, 0, 5, 2, 5],
       [2, 3, 3, 2, 3, 2, 4, 5],
       [7, 3, 5, 6, 3, 5, 6, 4],
       [1, 3, 7, 5, 1, 1, 2, 6],
       [2, 3, 3, 7, 7, 7, 7, 1],
       [4, 5, 4, 6, 1, 1, 1, 7],
       [0, 1, 5, 1, 1, 3, 5, 2],
       [1, 2, 4, 2, 6, 7, 1, 6],
       [6,

In [30]:

def calcular_aptitud(poblacion: npt.NDArray[np.int8]) -> list[int]:
    """Calcula el número de conflictos (aptitud o fitness)."""
    fitnes: list[int] = []
    # TODO: Calcula el número de conflictos si un par de reinas están en la misma fila
    # o si están en la misma diagonal.
    # No pueden estar en la misma columna debido a que la representación no lo permite,
    # solo hay una reina por columna.
    for individuo in poblacion:
        conflictos: int = 0
        for i in range(8):
            for k in range(i+1, 8):
                if individuo[i] == individuo[k]:
                    conflictos += 1
                if abs(i - k) == abs(individuo[i] - individuo[k]):
                    conflictos += 1
        fitnes.append(conflictos)
    return fitnes

In [31]:
aptitud = calcular_aptitud(poblacion)

In [32]:
poblacion = list(zip(poblacion, aptitud))


In [33]:
poblacion

[(array([1, 5, 4, 3, 7, 3, 7, 5], dtype=int32), 8),
 (array([2, 4, 3, 5, 0, 6, 4, 3], dtype=int32), 7),
 (array([1, 1, 0, 5, 4, 1, 7, 5], dtype=int32), 9),
 (array([2, 5, 4, 0, 4, 5, 1, 5], dtype=int32), 7),
 (array([1, 5, 2, 7, 4, 1, 3, 3], dtype=int32), 7),
 (array([0, 5, 3, 5, 2, 4, 0, 7], dtype=int32), 6),
 (array([3, 0, 2, 3, 5, 7, 5, 3], dtype=int32), 6),
 (array([1, 0, 0, 5, 6, 5, 6, 7], dtype=int32), 9),
 (array([0, 0, 1, 3, 6, 7, 4, 6], dtype=int32), 8),
 (array([6, 0, 6, 7, 3, 1, 1, 3], dtype=int32), 9),
 (array([0, 4, 7, 4, 6, 5, 4, 0], dtype=int32), 9),
 (array([6, 0, 2, 3, 5, 6, 6, 6], dtype=int32), 12),
 (array([2, 3, 5, 0, 3, 3, 2, 2], dtype=int32), 9),
 (array([0, 0, 0, 1, 0, 6, 7, 5], dtype=int32), 11),
 (array([2, 4, 3, 2, 7, 1, 4, 0], dtype=int32), 6),
 (array([1, 0, 3, 2, 4, 1, 1, 2], dtype=int32), 9),
 (array([2, 1, 6, 5, 6, 5, 2, 5], dtype=int32), 14),
 (array([0, 6, 0, 4, 0, 6, 6, 4], dtype=int32), 11),
 (array([0, 5, 3, 4, 4, 6, 0, 4], dtype=int32), 10),
 (array

In [34]:

def seleccionar_padres(
    poblacion: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    """Selecciona dos padres usando selección por torneo."""

    # TODO: Seleccionar de forma aleatoria 4 individuos
    # Sugerencia usar: random.sample

    torneo: list[int] = random.sample(poblacion, 4) # O usar otra representación para seleccionar, 
                             # como empaquetar a los individuos (padres) junto con su aptitud


    # Ordenar a los individuos seleccionados de acuerdo a la aptitud y seleccionar a los 2 mejores
    candidatos_ordenados = sorted(torneo, key=lambda x: x[1])

    padre1: npt.NDArray[np.int8] = candidatos_ordenados[0]
    padre2: npt.NDArray[np.int8] = candidatos_ordenados[1]

    return padre1, padre2


In [35]:
padre1, padre2 = seleccionar_padres(poblacion)
print(padre1)
print(padre2)

(array([3, 4, 5, 1, 2, 0, 2, 7], dtype=int32), 6)
(array([4, 2, 7, 1, 3, 4, 5, 0], dtype=int32), 7)


In [36]:

def cruzar(
    padre1: npt.NDArray[np.int8],
    padre2: npt.NDArray[np.int8]
) -> tuple[npt.NDArray[np.int8], npt.NDArray[np.int8]]:
    
    """Realiza crossover entre dos padres."""

    # TODO: Obtener un punto de cruza aleatorio y obtener dos hijos

    punto_cruce: int = random.randint(1,6)

    crom_padre1: list= padre1[0]
    crom_padre2: list = padre2[0]


    hijo1: npt.NDArray[np.int8] = np.concatenate((crom_padre1[:punto_cruce],crom_padre2[punto_cruce:]))
    hijo2: npt.NDArray[np.int8] = np.concatenate((crom_padre2[:punto_cruce], crom_padre1[punto_cruce:]))

    return hijo1, hijo2


In [37]:
hijo1, hijo2 = cruzar(padre1, padre2)

In [38]:
print(hijo1)
print(hijo2)

[3 4 5 1 3 4 5 0]
[4 2 7 1 2 0 2 7]


In [39]:
def mutar(
    individuo: npt.NDArray[np.int8],
    tasa_mutacion: float = 0.1
) -> npt.NDArray[np.int8]:
    """Realiza mutación con una probabilidad dada."""

    if np.random.random() < tasa_mutacion:
        # Se aplica la mutación, solo si pasó el umbral aleatorio.

        # TODO: obtener de forma aleatoria la posición del gen por sustituir,
        # con un nuevo valor aleatorio dentro del rango permitido [0, 7]

        valor_mutacion = random.randint(0,7)
        indice_mutacion = random.randint(0,7)
        individuo[indice_mutacion] = valor_mutacion

    return individuo


In [40]:
print("Antes: ", hijo1)
hijo_mutado = mutar(hijo1, 0.8)
print("Despues: ",hijo_mutado)

Antes:  [3 4 5 1 3 4 5 0]
Despues:  [3 4 5 1 3 4 5 4]


In [41]:

def algoritmo_genetico() -> npt.NDArray[np.int8] | None:
    """Resuelve el problema de las 8 reinas usando un algoritmo genético."""

    # Parámetros
    # TODO: Definir los parámetros
    tamano_poblacion: int = 100
    max_generaciones: int = 300
    tasa_mutacion: float = 0.10

    # TODO: Generar población inicial
    poblacion: npt.NDArray[np.int8] = generar_poblacion()

    for generacion in range(max_generaciones):

        # TODO: Calcular aptitudes de toda la población para verificar si ya hay una solución
        aptitudes: npt.NDArray[np.int8] = calcular_aptitud(poblacion)

        # TODO: Verificar si hay solución
        if 0 in aptitudes:
            posicion = aptitudes.index(0)
            return poblacion[posicion]
        # Si hay solución termina el algoritmo, y retornar la solución
        # De lo contrario continua con el proceso de evolución

        # Nueva generación
        nueva_poblacion: list[npt.NDArray[np.int8]] = []

        padre1: npt.NDArray[np.int8]
        padre2: npt.NDArray[np.int8]
        hijo1: npt.NDArray[np.int8]
        hijo2: npt.NDArray[np.int8]
        
        poblacion_con_aptitud = list(zip(poblacion, aptitudes))

        for _ in range(tamano_poblacion // 2):
            padre1, padre2 = seleccionar_padres(poblacion_con_aptitud)

            hijo1, hijo2 = cruzar(padre1, padre2)

            hijo1 = mutar(hijo1, tasa_mutacion)
            hijo2 = mutar(hijo2, tasa_mutacion)

            # Construye a la nueva población con los hijos
            nueva_poblacion.append(hijo1)
            nueva_poblacion.append(hijo2)

        # Sustituye a la población completa de padres por los hijos
        poblacion = np.array(nueva_poblacion, dtype=np.int8)

    print("No se encontró solución en el número máximo de generaciones.")
    return None

In [67]:
# Ejecutar el algoritmo genético

solucion: npt.NDArray[np.int8] | None = algoritmo_genetico()

print(solucion)
solucion = list(solucion)
if solucion is not None:
    imprimir_tablero(solucion)


[5 3 6 0 2 4 1 7]
+---+---+---+---+---+---+---+---+
|   |   |   | Q |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   | Q |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   | Q |   |   |   |
+---+---+---+---+---+---+---+---+
|   | Q |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   | Q |   |   |
+---+---+---+---+---+---+---+---+
| Q |   |   |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   | Q |   |   |   |   |   |
+---+---+---+---+---+---+---+---+
|   |   |   |   |   |   |   | Q |
+---+---+---+---+---+---+---+---+
