In [2]:
import numpy as np
import numpy.typing as npt

poblacion: npt.NDArray[np.int_] = np.random.randint(0, 3, size=(10, 20), dtype=int)

print("Población inicial:")
print(poblacion)

Población inicial:
[[1 0 0 1 2 0 0 0 2 0 2 2 1 0 0 2 0 0 1 1]
 [1 1 0 2 2 1 1 1 0 1 1 0 0 1 2 2 0 0 1 2]
 [1 2 1 0 1 2 0 0 2 2 0 2 1 0 1 2 0 0 1 0]
 [1 1 0 2 0 1 1 1 1 2 2 1 2 0 2 0 2 2 1 0]
 [1 2 0 1 0 2 1 1 2 0 0 2 1 1 0 1 1 0 2 2]
 [1 0 2 2 2 2 0 1 0 1 0 1 0 1 2 0 2 1 0 0]
 [1 0 2 1 2 0 0 1 0 2 0 2 2 2 1 1 2 1 1 0]
 [2 0 1 1 1 2 0 2 2 2 0 0 0 0 1 0 1 1 2 1]
 [2 0 2 1 0 1 0 2 2 2 1 1 1 1 0 2 1 1 1 2]
 [1 1 1 2 0 0 0 0 2 1 1 0 0 1 1 1 0 2 2 1]]


In [3]:
tercer_individuo: npt.NDArray[np.int_] = poblacion[2]
print("\nCromosoma del tercer individuo:")
print(tercer_individuo)


Cromosoma del tercer individuo:
[1 2 1 0 1 2 0 0 2 2 0 2 1 0 1 2 0 0 1 0]


In [4]:
primeros_5_genes: npt.NDArray[np.int_] = poblacion[:, :5]
print("\nPrimeros 5 genes de todos los individuos:")
print(primeros_5_genes)


Primeros 5 genes de todos los individuos:
[[1 0 0 1 2]
 [1 1 0 2 2]
 [1 2 1 0 1]
 [1 1 0 2 0]
 [1 2 0 1 0]
 [1 0 2 2 2]
 [1 0 2 1 2]
 [2 0 1 1 1]
 [2 0 2 1 0]
 [1 1 1 2 0]]


In [5]:
indice_individuo: int = np.random.randint(0, 10)
indice_individuo

6

In [6]:

individuo_mutado: npt.NDArray[np.int_] = poblacion[indice_individuo].copy()
individuo_mutado

array([1, 0, 2, 1, 2, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 1, 2, 1, 1, 0])

In [7]:

ultimo_gen_actual: int = individuo_mutado[-1]
ultimo_gen_actual

np.int64(0)

In [8]:
alelos_posibles: list[int] = [0, 1, 2]
alelos_posibles.remove(ultimo_gen_actual)

nuevo_alelo: int = np.random.choice(alelos_posibles)

individuo_mutado[-1] = nuevo_alelo

print("\nIndividuo seleccionado para mutación:", indice_individuo)
print("Antes de la mutación:", poblacion[indice_individuo])
print("Después de la mutación:", individuo_mutado)


Individuo seleccionado para mutación: 6
Antes de la mutación: [1 0 2 1 2 0 0 1 0 2 0 2 2 2 1 1 2 1 1 0]
Después de la mutación: [1 0 2 1 2 0 0 1 0 2 0 2 2 2 1 1 2 1 1 1]


In [9]:
import numpy as np
import numpy.typing as npt

# Matriz A: 10 individuos, 10 genes cada uno
A: npt.NDArray[np.int_] = np.array([
    [1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0, 0, 1, 1, 0, 1],
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
    [0, 0, 1, 1, 1, 0, 0, 1, 1, 0],
    [1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
    [1, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
    [1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
])

In [10]:
import random
indices: list = random.sample(range(A.shape[0]), 2)

padre1: npt.NDArray[np.int_] = A[indices[0]]
padre2: npt.NDArray[np.int_] = A[indices[1]]

print("Padre 1 (individuo", indices[0], "):", padre1)
print("Padre 2 (individuo", indices[1], "):", padre2)

Padre 1 (individuo 4 ): [1 0 0 1 1 1 0 1 0 1]
Padre 2 (individuo 1 ): [0 1 0 1 0 0 1 1 0 1]


In [11]:
genes_padre1: int = int(np.sum(padre1))
genes_padre2: int = int(np.sum(padre2))

print("\nCantidad de genes activos (1):")
print("Padre 1:", genes_padre1)
print("Padre 2:", genes_padre2)


Cantidad de genes activos (1):
Padre 1: 6
Padre 2: 5


In [12]:
if genes_padre1 > genes_padre2:
    print("El Padre 1 tiene mayor aptitud.")
elif genes_padre2 > genes_padre1:
    print("El Padre 2 tiene mayor aptitud.")
else:
    print("Ambos padres tienen la misma aptitud.")

El Padre 1 tiene mayor aptitud.


In [13]:
punto_corte: int = 5

hijo1: npt.NDArray[np.int_] = np.concatenate((padre1[:punto_corte], padre2[punto_corte:]))
hijo2: npt.NDArray[np.int_] = np.concatenate((padre2[:punto_corte], padre1[punto_corte:]))

In [14]:
print("Padre 1:", padre1)
print("Padre 2:", padre2)

print("\nHijo 1:", hijo1)
print("Hijo 2:", hijo2)

Padre 1: [1 0 0 1 1 1 0 1 0 1]
Padre 2: [0 1 0 1 0 0 1 1 0 1]

Hijo 1: [1 0 0 1 1 0 1 1 0 1]
Hijo 2: [0 1 0 1 0 1 0 1 0 1]


In [15]:
import random
import numpy as np
import numpy.typing as npt

# Lista de tuplas: (Cromosoma de 8 genes, Fitness)
poblacion_completa: list[tuple[list[int], float]] = [
    ([1, 1, 1, 10, 1, 0, 1, 0], 5.6), ([1, 1, 1, 10, 1, 0, 1, 1], 6.8),
    ([0, 0, 1, 5, 0, 1, 1, 0], 9.2),  ([1, 0, 1, 8, 1, 1, 0, 0], 4.1),
    ([0, 1, 0, 3, 0, 0, 1, 1], 7.5),  ([1, 1, 0, 12, 1, 0, 0, 1], 3.2),
    ([0, 0, 0, 2, 0, 1, 1, 1], 8.9),  ([1, 0, 0, 7, 1, 1, 1, 0], 5.0),
    ([0, 1, 1, 4, 0, 0, 0, 1], 6.3),  ([1, 1, 1, 15, 0, 0, 1, 1], 2.1),
    ([0, 0, 1, 1, 1, 1, 0, 0], 9.8),  ([1, 0, 1, 9, 0, 1, 0, 1], 4.7),
    ([0, 1, 0, 6, 1, 0, 1, 0], 5.9),  ([1, 1, 0, 11, 0, 0, 0, 0], 3.8),
    ([0, 0, 0, 5, 1, 1, 1, 1], 7.1),  ([1, 0, 0, 3, 0, 1, 1, 0], 8.2),
    ([0, 1, 1, 8, 1, 0, 0, 1], 4.5),  ([1, 1, 1, 2, 0, 1, 0, 1], 8.5),
    ([0, 0, 1, 10, 0, 0, 1, 1], 3.9), ([0, 1, 0, 4, 1, 1, 0, 0], 7.8)
]

In [16]:
candidatos: list = random.sample(poblacion_completa, 3)

print("Candidatos seleccionados:")
for c in candidatos:
    print(c)

Candidatos seleccionados:
([1, 0, 0, 3, 0, 1, 1, 0], 8.2)
([1, 1, 1, 10, 1, 0, 1, 0], 5.6)
([1, 1, 0, 12, 1, 0, 0, 1], 3.2)


In [17]:
candidatos_ordenados = sorted(candidatos, key=lambda x: x[1], reverse=True)

print("\nCandidatos ordenados por fitness:")
for c in candidatos_ordenados:
    print(c)


Candidatos ordenados por fitness:
([1, 0, 0, 3, 0, 1, 1, 0], 8.2)
([1, 1, 1, 10, 1, 0, 1, 0], 5.6)
([1, 1, 0, 12, 1, 0, 0, 1], 3.2)


In [18]:
padre1: tuple = candidatos_ordenados[0]
padre2: tuple = candidatos_ordenados[1]

In [19]:
crom_padre1: list= padre1[0]
crom_padre2: list = padre2[0]

print("\nPadre 1:", crom_padre1, "Fitness:", padre1[1])
print("Padre 2:", crom_padre2, "Fitness:", padre2[1])


Padre 1: [1, 0, 0, 3, 0, 1, 1, 0] Fitness: 8.2
Padre 2: [1, 1, 1, 10, 1, 0, 1, 0] Fitness: 5.6


In [20]:
punto_cruce: int = 4

hijo1: list = crom_padre1[:punto_cruce] + crom_padre2[punto_cruce:]
hijo2: list = crom_padre2[:punto_cruce] + crom_padre1[punto_cruce:]

In [21]:
print("\nResultado del cruce:")
print("Hijo 1:", hijo1)
print("Hijo 2:", hijo2)


Resultado del cruce:
Hijo 1: [1, 0, 0, 3, 1, 0, 1, 0]
Hijo 2: [1, 1, 1, 10, 0, 1, 1, 0]


In [22]:
P = np.array ([[1.2, 3.4, 2.1, 4.0, 0.9],
[2.5, 1.1, 3.3, 0.8, 4.2],
[0.7, 2.9, 1.5, 3.6, 2.1],
[4.1, 0.5, 2.7, 1.9, 3.3],
[1.8, 3.0, 4.2, 0.6, 2.4],
[2.9, 1.7, 0.9, 3.4, 1.2],
[3.3, 2.2, 1.4, 4.1, 0.5],
[0.6, 4.3, 2.5, 1.1, 3.7],
[1.9, 2.6, 3.8, 0.7, 4.0],
[2.4, 0.9, 4.1, 2.3, 1.6],
[3.7, 1.8, 2.0, 4.4, 0.8],
[1.1, 3.9, 0.6, 2.5, 3.0],
[2.2, 4.0, 1.7, 3.1, 0.4],
[4.3, 2.1, 3.5, 1.0, 2.7],
[0.8, 1.5, 4.4, 2.9, 3.2],
[1.6, 3.2, 2.8, 0.5, 4.1],
[2.7, 0.4, 3.9, 1.6, 2.5],
[3.9, 2.8, 0.7, 4.2, 1.3],
[0.5, 4.1, 2.6, 3.0, 1.9],
[1.4, 2.7, 3.2, 4.3, 0.6],
[2.1, 3.5, 1.0, 2.4, 4.4],
[3.5, 0.8, 2.3, 1.2, 3.8],
[4.0, 1.9, 3.1, 2.8, 0.7],
[0.9, 2.4, 4.3, 3.5, 1.5],
[1.7, 3.6, 2.9, 0.4, 4.0],
[2.8, 1.3, 3.6, 4.0, 0.9],
[3.1, 2.5, 0.8, 1.7, 3.4],
[4.2, 0.6, 2.4, 3.9, 1.1],
[0.4, 3.1, 1.9, 2.6, 4.3],
[1.5, 4.2, 3.0, 0.9, 2.8]])

In [23]:
fitness = np.sum(P ** 2, axis=1)
fitness

array([34.22, 36.63, 28.52, 38.85, 36.  , 25.11, 34.75, 40.  , 41.3 ,
       31.23, 40.93, 32.03, 33.5 , 43.44, 40.9 , 37.7 , 31.47, 42.87,
       36.43, 38.34, 42.78, 34.06, 37.55, 39.56, 40.42, 39.3 , 30.95,
       40.18, 38.63, 37.54])

In [24]:
mejor_individuo = np.max(fitness)
mejor_individuo

np.float64(43.44)

In [25]:
peor_individuo = np.min(fitness)
peor_individuo

np.float64(25.110000000000003)

In [26]:
fitness_promedio = np.mean(fitness)
fitness_promedio

np.float64(36.839666666666666)

In [27]:
fitness_std = np.std(fitness)
fitness_std

np.float64(4.40806116362083)

In [44]:
P_normalizada = ((P - np.min(P)) / ((np.max(P)) - (np.min(P))))
P_normalizada

array([[0.2  , 0.75 , 0.425, 0.9  , 0.125],
       [0.525, 0.175, 0.725, 0.1  , 0.95 ],
       [0.075, 0.625, 0.275, 0.8  , 0.425],
       [0.925, 0.025, 0.575, 0.375, 0.725],
       [0.35 , 0.65 , 0.95 , 0.05 , 0.5  ],
       [0.625, 0.325, 0.125, 0.75 , 0.2  ],
       [0.725, 0.45 , 0.25 , 0.925, 0.025],
       [0.05 , 0.975, 0.525, 0.175, 0.825],
       [0.375, 0.55 , 0.85 , 0.075, 0.9  ],
       [0.5  , 0.125, 0.925, 0.475, 0.3  ],
       [0.825, 0.35 , 0.4  , 1.   , 0.1  ],
       [0.175, 0.875, 0.05 , 0.525, 0.65 ],
       [0.45 , 0.9  , 0.325, 0.675, 0.   ],
       [0.975, 0.425, 0.775, 0.15 , 0.575],
       [0.1  , 0.275, 1.   , 0.625, 0.7  ],
       [0.3  , 0.7  , 0.6  , 0.025, 0.925],
       [0.575, 0.   , 0.875, 0.3  , 0.525],
       [0.875, 0.6  , 0.075, 0.95 , 0.225],
       [0.025, 0.925, 0.55 , 0.65 , 0.375],
       [0.25 , 0.575, 0.7  , 0.975, 0.05 ],
       [0.425, 0.775, 0.15 , 0.5  , 1.   ],
       [0.775, 0.1  , 0.475, 0.2  , 0.85 ],
       [0.9  , 0.375, 0.675, 0.6

In [29]:
fitness_norm = np.sum(P_normalizada ** 2, axis=1)
fitness_norm

array([1.60875 , 1.744375, 1.2925  , 1.853125, 1.7     , 1.114375,
       1.646875, 1.94    , 1.98125 , 1.436875, 1.973125, 1.496875,
       1.57375 , 2.085   , 1.96625 , 1.79625 , 1.461875, 2.084375,
       1.721875, 1.83625 , 2.05375 , 1.59875 , 1.771875, 1.8925  ,
       1.94625 , 1.87625 , 1.409375, 1.95125 , 1.849375, 1.77625 ])

In [30]:
mejor_individuo_norm = np.max(fitness_norm)
mejor_individuo_norm

np.float64(2.085)

In [ ]:
peor_individuo_norm = np.min(fitness_norm)
peor_individuo_norm

np.float64(1.114375)

In [32]:
fitness_promedio_norm = np.mean(fitness_norm)
fitness_promedio_norm

np.float64(1.7479791666666666)

In [33]:
fitness_std_norm = np.std(fitness_norm)
fitness_std_norm 

np.float64(0.23882708634101557)

In [50]:
ruido: npt.NDArray[np.float64] = np.random.normal(loc=0.05, scale=0.02,size=(P.shape))
ruido


array([[ 0.06012156,  0.06231642,  0.07049528,  0.02444712,  0.03811724],
       [ 0.05117525,  0.0552626 ,  0.06966845,  0.0719881 ,  0.03111362],
       [ 0.07427681,  0.02902837,  0.03046338,  0.04807004,  0.04901356],
       [ 0.04196664,  0.04618063,  0.03421119,  0.04130207,  0.05727813],
       [ 0.05744113,  0.03321422,  0.05478237,  0.06009665,  0.02783649],
       [ 0.02984019,  0.05491092,  0.07105883,  0.0469167 ,  0.09767616],
       [ 0.07082858,  0.02358983,  0.04533193,  0.07733165,  0.07525621],
       [ 0.05856761,  0.04426233,  0.10117388,  0.05190791,  0.04765319],
       [ 0.05833083,  0.04979721,  0.03783662,  0.03339308,  0.0583163 ],
       [ 0.07771589,  0.05362659,  0.05052717,  0.0553877 ,  0.01762863],
       [ 0.05527181,  0.02459942,  0.06511777,  0.03936516,  0.04716191],
       [ 0.07019948,  0.06103136,  0.03900188,  0.06183457,  0.10210527],
       [ 0.0493178 ,  0.04790454,  0.03917503,  0.03761487,  0.01998587],
       [ 0.02481546,  0.0406606 ,  0.0

In [51]:
ruido = np.clip(ruido, 0, 0.1)
ruido

array([[0.06012156, 0.06231642, 0.07049528, 0.02444712, 0.03811724],
       [0.05117525, 0.0552626 , 0.06966845, 0.0719881 , 0.03111362],
       [0.07427681, 0.02902837, 0.03046338, 0.04807004, 0.04901356],
       [0.04196664, 0.04618063, 0.03421119, 0.04130207, 0.05727813],
       [0.05744113, 0.03321422, 0.05478237, 0.06009665, 0.02783649],
       [0.02984019, 0.05491092, 0.07105883, 0.0469167 , 0.09767616],
       [0.07082858, 0.02358983, 0.04533193, 0.07733165, 0.07525621],
       [0.05856761, 0.04426233, 0.1       , 0.05190791, 0.04765319],
       [0.05833083, 0.04979721, 0.03783662, 0.03339308, 0.0583163 ],
       [0.07771589, 0.05362659, 0.05052717, 0.0553877 , 0.01762863],
       [0.05527181, 0.02459942, 0.06511777, 0.03936516, 0.04716191],
       [0.07019948, 0.06103136, 0.03900188, 0.06183457, 0.1       ],
       [0.0493178 , 0.04790454, 0.03917503, 0.03761487, 0.01998587],
       [0.02481546, 0.0406606 , 0.0644929 , 0.08912618, 0.01452696],
       [0.06567452, 0.05419819, 0.

In [59]:
P_mutado = P_normalizada + ruido
P_mutado = np.clip(P_mutado,0, 1)
P_mutado

array([[0.26012156, 0.81231642, 0.49549528, 0.92444712, 0.16311724],
       [0.57617525, 0.2302626 , 0.79466845, 0.1719881 , 0.98111362],
       [0.14927681, 0.65402837, 0.30546338, 0.84807004, 0.47401356],
       [0.96696664, 0.07118063, 0.60921119, 0.41630207, 0.78227813],
       [0.40744113, 0.68321422, 1.        , 0.11009665, 0.52783649],
       [0.65484019, 0.37991092, 0.19605883, 0.7969167 , 0.29767616],
       [0.79582858, 0.47358983, 0.29533193, 1.        , 0.10025621],
       [0.10856761, 1.        , 0.625     , 0.22690791, 0.87265319],
       [0.43333083, 0.59979721, 0.88783662, 0.10839308, 0.9583163 ],
       [0.57771589, 0.17862659, 0.97552717, 0.5303877 , 0.31762863],
       [0.88027181, 0.37459942, 0.46511777, 1.        , 0.14716191],
       [0.24519948, 0.93603136, 0.08900188, 0.58683457, 0.75      ],
       [0.4993178 , 0.94790454, 0.36417503, 0.71261487, 0.01998587],
       [0.99981546, 0.4656606 , 0.8394929 , 0.23912618, 0.58952696],
       [0.16567452, 0.32919819, 1.

In [60]:
fitness_mutado = np.sum(P_mutado ** 2, axis=1)
fitness_mutado

array([1.85424647, 2.00866057, 1.48725621, 2.09649592, 1.92352257,
       1.33527437, 1.9549027 , 2.21542272, 2.26590537, 1.69951543,
       2.15319436, 1.85107364, 1.78868412, 2.32594244, 2.09559652,
       2.05901958, 1.70992517, 2.30482241, 1.97726298, 2.04956917,
       2.28068512, 1.85041537, 2.05500203, 2.1163451 , 2.12999755,
       2.18375135, 1.70993634, 2.16568406, 2.03103027, 1.9853069 ])

In [61]:
mejor_individuo_mutado = np.max(fitness_mutado)
mejor_individuo_mutado

np.float64(2.325942441113089)

In [62]:
peor_individuo_mutado = np.min(fitness_mutado)
peor_individuo_mutado 

np.float64(1.3352743707614063)

In [63]:
fitness_promedio_mutado = np.mean(fitness_mutado)
fitness_promedio_mutado

np.float64(1.988814893603289)

In [64]:
fitness_std_mutado = np.std(fitness_mutado)
fitness_std_mutado

np.float64(0.2321837231134218)