Ejercicio 1: Creación de Población y Operador de Mutación
Contexto en Computación Evolutiva:
Un algoritmo evolutivo inicia con una población inicial aleatoria. En este caso, cada individuo tiene 20 genes y cada gen puede tener tres estados posibles (alelos: 0, 1 o 2), lo cual podría representar, por ejemplo, diferentes tipos de proteínas o niveles de una señal. La Mutación es el proceso que altera estos valores para descubrir nuevas soluciones.
Instrucciones:

Crear la Población: Generar una matriz de 10 x 20 (10 individuos, 20 genes) con valores aleatorios enteros entre 0 y 2 inclusive.
Utilizar los type hints adecuados para asegurar que la matriz sea de enteros.
Exploración de Individuos: Extrae y muestra el cromosoma del tercer individuo. Extraer y mostrar los primeros 5 genes de todos los individuos.
Mutación: Extraer un individuo al azar y altera su último gen con un valor del alelo aleatorio permitido entre 0 y 2 inclusive, pero no puede ser el mismo valor que tiene. (un valor que represente una mutación). Imprimir al individuo mutado para verificar el cambio.

In [2]:
import numpy as np
import numpy.typing as npt

poblacion: npt.NDArray[np.long] = np.random.randint(0, 3, size=(10, 20))

In [5]:
print(poblacion)

[[1 0 0 2 1 1 1 2 0 2 2 2 1 0 2 1 0 2 2 2]
 [2 2 0 0 1 1 2 1 1 1 1 1 0 1 0 1 0 0 2 2]
 [1 0 2 0 2 2 1 2 0 1 0 0 2 1 0 0 0 1 1 2]
 [2 2 2 2 0 1 2 0 2 2 0 0 1 2 2 1 1 2 0 0]
 [2 0 2 0 1 1 2 1 0 0 2 1 0 2 1 1 0 2 1 2]
 [1 0 1 0 1 1 1 0 1 1 1 2 2 2 1 1 1 2 2 2]
 [1 2 2 2 2 0 1 1 1 2 2 2 2 2 0 2 0 1 2 1]
 [0 1 2 0 2 1 0 0 1 2 2 1 1 0 2 2 2 1 2 0]
 [0 0 2 0 2 1 2 2 0 2 0 0 0 2 0 1 0 1 1 1]
 [2 2 2 0 0 1 0 0 2 2 0 0 2 1 0 2 0 0 2 1]]


In [7]:
gen:npt.NDArray[np.long] = poblacion[4]
print("Cromosoma tercer individuo: ", gen)

Cromosoma tercer individuo:  [2 0 2 0 1 1 2 1 0 0 2 1 0 2 1 1 0 2 1 2]


In [16]:
for p in poblacion:
    print("Genes: ", p[:5])

Genes:  [1 0 0 2 1]
Genes:  [2 2 0 0 1]
Genes:  [1 0 2 0 2]
Genes:  [2 2 2 2 0]
Genes:  [2 0 2 0 1]
Genes:  [1 0 1 0 1]
Genes:  [1 2 2 2 2]
Genes:  [0 1 2 0 2]
Genes:  [0 0 2 0 2]
Genes:  [2 2 2 0 0]


In [125]:
import random

mutado = random.sample(poblacion.tolist(), 1)
print(mutado)
print(mutado[0][19])

[[2, 0, 2, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 2, 1, 1, 0, 2, 1, 2]]
2


In [126]:


gen_mutar = random.randint(0,3)
print(gen_mutar)
print(mutado[0][19])

if gen_mutar == mutado[0][19]:
    while (gen_mutar == mutado[0][19]):
        gen_mutar = random.randint(0,3)
        
        if mutado[0][19] != gen_mutar:
            mutado[0][19] = gen_mutar
            break
else:
    mutado[0][19] = gen_mutar
mutado

0
2


[[2, 0, 2, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 2, 1, 1, 0, 2, 1, 0]]


Ejercicio 2: Selección, Análisis y Recombinación de 10 Genes
Dada la matriz A que representa una población, que contiene 10 individuos y 10 genes por cada individuo:
Instrucciones:

    Selección Aleatoria: Utilizando la matriz A, seleccionar de forma aleatoria dos filas que representarán al Padre 1 y al Padre 2. Asegurar que no se seleccione el mismo individuo dos veces.
    Análisis de Densidad Genética:
        Calcular y mosstrar cuántos genes están encendidos (1) en cada padre.
        Determinar cuál de los dos padres tiene una mayor "aptitud" (asumiendo que a mayor cantidad de 1s, mejor es el individuo).
    Cruce de Punto Fijo:
        Realiza un cruce de 1 punto utilizando el índice 5 como punto de corte (la mitad exacta del cromosoma).
        El Hijo 1 debe tener los primeros 5 genes del Padre 1 y los últimos 5 del Padre 2.
        El Hijo 2 debe tener los primeros 5 genes del Padre 2 y los últimos 5 del Padre 1.
    Validación de Herencia: Imprime los cromosomas de los padres y de los dos hijos resultantes para verificar visualmente que el intercambio de información genética fue correcto.

# Matriz A: 10 individuos, 10 genes cada uno
A: npt.NDArray[np.int_] = np.array([
    [1, 0, 1, 0, 1, 1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0, 0, 1, 1, 0, 1],
    [1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
    [0, 0, 1, 1, 1, 0, 0, 1, 1, 0],
    [1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
    [0, 1, 1, 0, 0, 0, 1, 0, 1, 1],
    [1, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
    [1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
    [0, 1, 0, 0, 1, 0, 0, 1, 0, 1]
])



In [129]:
A = np.random.randint(0,2, (10,10))
A


array([[1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 1],
       [1, 1, 1, 1, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0, 1, 0, 0, 0, 0]])

In [130]:
len(A)

10

In [ ]:
indice1 = 0
indice2 = 0
 
while indice1 == indice2:
    indice1 = random.randint(0, len(A))
    indice2 = random.randint(0, len(A))
    